# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515fd08e0f77d5ec14d1ada02c8912e4259c37db0437e8db7b321c6a42e1ec3909d61b468fc43be6abc69c37616a8cb9afaa945e698e39cdce750ab8e2bdd2c1

test:
  secret_key_base: 3e6e6e3a7a7a905308e207b6866374289b1dea0c9feee40d93e3656a3a737637236d1d1f34245aa3d119e736a0c1dd328d64f0861eea977777f8aa84a031bb52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
